name: 'update-repo'
description: 'Radxa apt repos management'
inputs:
  test-repo:
    default: false
  reset:
    default: false
  token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Update radxa-repo/bullseye${{ inputs.test-repo && '-test' }}
      if: 
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ inputs.token }}
        repository: radxa-repo/bullseye${{ inputs.test-repo && '-test' }}
        event-type: ${{ inputs.reset && 'reset_repo' || 'new_package_release' }}

    - name: Update radxa-repo/buster${{ inputs.test-repo && '-test' }}
      if: 
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ inputs.token }}
        repository: radxa-repo/buster${{ inputs.test-repo && '-test' }}
        event-type: ${{ inputs.reset && 'reset_repo' || 'new_package_release' }}

    - name: Update radxa-repo/jammy${{ inputs.test-repo && '-test' }}
      if: 
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ inputs.token }}
        repository: radxa-repo/jammy${{ inputs.test-repo && '-test' }}
        event-type: ${{ inputs.reset && 'reset_repo' || 'new_package_release' }}

    - name: Update radxa-repo/focal${{ inputs.test-repo && '-test' }}
      if: 
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ inputs.token }}
        repository: radxa-repo/focal${{ inputs.test-repo && '-test' }}
        event-type: ${{ inputs.reset && 'reset_repo' || 'new_package_release' }}
