name: Reset Production repos
on:
  workflow_dispatch:

permissions: {}

jobs:
  reset-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: radxa-repo/update-repo-action@main
        with:
          reset: true
          token: ${{ secrets.RADXA_APT_TEST_REPO_TOKEN }}
