name: Reset Test repos
on:
  workflow_dispatch:

permissions: {}

jobs:
  update-test:
    runs-on: ubuntu-latest
    steps:
      - name: Update Test repos
        uses: radxa-repo/update-repo-action@main
        with:
          reset: true
          test-repo: true
          token: ${{ secrets.RADXA_APT_TEST_REPO_TOKEN }}
