name: Update Test repos
on:
  workflow_dispatch:

permissions: {}

jobs:
  update-test:
    runs-on: ubuntu-latest
    steps:
      - name: Update Test repos
        uses: RadxaOS-SDK/rsdk/.github/actions/infra-repo-update@main
        with:
          test-repo: true
          token: ${{ secrets.RADXA_APT_TEST_REPO_TOKEN }}
